### ISSUE TITLE
Deleted ping message causes error

### ISSUE THREAD

**Issue by ProditorMagnus** [ProditorMagnus/RadBot#1]
```
2021-10-18T16:14:21.163898+00:00 app[worker.1]: (node:22) UnhandledPromiseRejectionWarning: DiscordAPIError: Unknown Message
2021-10-18T16:14:21.163908+00:00 app[worker.1]:     at RequestHandler.execute (/app/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
2021-10-18T16:14:21.163908+00:00 app[worker.1]:     at runMicrotasks (<anonymous>)
2021-10-18T16:14:21.163909+00:00 app[worker.1]:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2021-10-18T16:14:21.163909+00:00 app[worker.1]:     at async RequestHandler.push (/app/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
2021-10-18T16:14:21.163910+00:00 app[worker.1]: (Use `node --trace-warnings ...` to show where the warning was created)
2021-10-18T16:14:21.163934+00:00 app[worker.1]: (node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2021-10-18T16:14:21.163962+00:00 app[worker.1]: (node:22) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ProditorMagnus** [comment]
When stopwatch reaction is missing, attempt to remove it crashes bot.

**Comment by ProditorMagnus** [comment]
Fixed.
